### ISSUE TITLE
Webapp\mongo db issue

### ISSUE THREAD

**Issue by n0tis** [codexgigassys/codex-backend#128]
Hello,

I was able to successfully deploy the docker instance and upload files via the files_to_load folder method, the only issue I am having is that when I go to the webpage on port 6100, the page is not completely rendering. The samples tab shows as "Samples :0 (loading...)", the "Search" button doesnt show anything in the dropdown list, and its not functional overall. Looking at the syslog messages shows a 404 not found for the script "ip.js" which I realize is part of the front-end portion of the application. The problem is I cant locate this ip.js file within all the docker images. I can hit the ip.js.sample file, which I should be able to just rename or no? Any thoughts?

Web log:
2018-10-25T20:04:50+00:00 172.18.0.1 httpd[1319]: 192.168.100.4 - - [25/Oct/2018:20:04:50 +0000] "GET /js/ip.js HTTP/1.1" 404 206

I used the method 2 install procedures. 

**Update:**
I was able to find that ip.js.sample and use it as ip.js. with this command (httpd container): 
sudo docker-compose exec httpd mv htdocs/js/ip.js.sample htdocs/js/ip.js

And now I dont get any 404's but its still not functional. The "Samples" button on the top still shows as loading and is not clickable.

**Comment by CrimsonGlory** [comment]
CodexGigas free software version has been discontinued on 2017-03-06. The development is still active on the propietary version.
ip.js should be edited with the IP of the backend, if file does not exist, 127.0.0.1 is used (which is the most common scenario). Not sure your setup, but try 192.168.100.4 or the IP where the codexbackend_api_1 container is running.

**Comment by n0tis** [comment]
Thanks for the response and update, CrimsonGlory. I actually updated that ip.js to the host servers IP address a few days back, not the container, and that seemed to get it functional. 

Is the proprietary version one that would be marketed\sold?

Also, may I have the pass to the apt-notes zip? I sent a DM on Twitter for the password.

**Comment by CrimsonGlory** [comment]
I asked the person who is in charge of the twitter account to reply your DM, as I don't have the password nor I created the zip file.

The propietary version is not marketed/sold (at least not yet (and it doesn't depend on me)). The software evolved into a big monster quite different from what we originally thought. We are using the software internally to retrieve data to provide other services.

**Comment by n0tis** [comment]
Perfect, thanks again!
