### ISSUE TITLE
Fails to start docker-compose

### ISSUE THREAD

**Issue by Indeserpen** [codexgigassys/codex-backend#2]
Installed all by README.md and getting this output when try to start:
root@kali:~/Codex/codex-backend# docker-compose start
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environ

I am running Kali Linux 2.0 Rolling 64 AMD 
root@kali:~# docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Tue, 12 Jul 2016 07:46:35 -0700
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
root@kali:~# docker-compose version
docker-compose version 1.5.2, build unknown
docker-py version: 1.7.2
CPython version: 2.7.12+
OpenSSL version: OpenSSL 1.0.2h  3 May 2016

**Comment by CrimsonGlory** [comment]
Hi, it seems the Docker deamon is not running. 
Check if /usr/bin/dockerd is running

```
$ ps aux | grep "dockerd"
user       5408  0.0  0.0  21296  1096 pts/11   R+   11:07   0:00 grep --color=auto dockerd
root     19276  0.0  0.8 403268 49804 ?        Ssl  08:55   0:07 /usr/bin/dockerd -H fd://
```

If it's not, please try:
`# service docker start`.

Output of `docker version` will look something like this:

```
# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

**Comment by Indeserpen** [comment]
Yes this was it, stupid from my side to not think figure it out! Thanks and wonderful framework!
